(()=>{"use strict";
const state=()=>window.p20State?window.p20State():({data:{locations:[],sections:[],assignments:[],researchers:[],sectors:[],links:[]},access:null,session:"",token:""});
const escv=v=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");
const wa=t=>"https://wa.me/?text="+encodeURIComponent(t);
const originalApi=window.api;
if(originalApi){window.api=async function(action,body={},auth=true){const st=state();const h={"Content-Type":"application/json"};if(auth&&st.session)h["x-field-session"]=st.session;const endpoint=action==="import_database"?"https://oqqksddzwrlkqnfpfshu.supabase.co/functions/v1/field-import":(window.API||"https://oqqksddzwrlkqnfpfshu.supabase.co/functions/v1/field-access");const r=await fetch(endpoint,{method:"POST",headers:h,cache:"no-store",body:JSON.stringify({action,...body,_v:Date.now()})});const ct=r.headers.get("content-type")||"";let j={};if(!ct.includes("application/json")){throw new Error("O servidor retornou uma resposta inválida. Atualize a página e tente novamente.")}try{j=await r.json()}catch{throw new Error("O servidor retornou JSON inválido.")}if(!r.ok)throw new Error(j.error||"Erro no servidor");return j}}
window.copyLink=async function(u){try{await navigator.clipboard.writeText(u);alert("Link copiado.")}catch{prompt("Copie o link:",u)}};
window.regenerateAccess=async function(id){if(!id){alert("Este acesso não possui identificador.");return}try{const j=await window.api("regenerate_link",{id});await window.load();window.render(j.access?.role==="director"?"diretoria":"pesquisadores")}catch(e){alert(e.message||"Não foi possível gerar o novo link.")}};
window.refreshActive=async function(active){try{await window.load();window.render(active)}catch(e){alert("Não foi possível atualizar os dados: "+(e.message||"Erro"))}};
function researcherTable(){const st=state(),d=st.data||{},links=(d.links||[]).filter(x=>x.role==="researcher"&&x.active!==false),rs=d.researchers||[];const linkFor=r=>{const l=links.find(x=>x.id===r.access_link_id||((x.display_name||"").toLowerCase()===(r.full_name||"").toLowerCase()&&x.sector_id===r.sector_id));return r.access_url||l?.url||""};const rows=rs.map(r=>{const sec=(d.sectors||[]).find(s=>s.id===r.sector_id),u=linkFor(r),send=u?wa("Acesso Pesquisa 2.0 — Pesquisador\n"+u+"\nSenha inicial: 1234"):"";const link=u?'<div class="actions"><button class="btn small" data-copy="'+escv(u)+'">Copiar link</button><a class="btn success small" href="'+send+'" target="_blank" rel="noopener">WhatsApp</a></div><small class="muted" style="display:block;margin-top:5px;word-break:break-all">'+escv(u)+'</small>':'<div class="actions"><span class="muted">Link não disponível</span>'+(r.access_link_id?'<button class="btn small" data-reg="'+escv(r.access_link_id)+'">Gerar novo link</button>':'')+'</div>';return '<tr><td>'+escv(r.full_name)+'</td><td>'+escv(r.phone||"")+'</td><td>'+escv(sec?.name||"")+'</td><td>'+link+'</td><td><button class="btn danger small" data-del="'+escv(r.id)+'">Excluir</button></td></tr>'}).join("");return '<div class="table"><table><tr><th>Nome</th><th>Telefone</th><th>Setor</th><th>Link de acesso</th><th>Ações</th></tr>'+rows+'</table></div>'}
function patchResearchers(){const st=state();if(st.access?.role!=="admin")return;const cards=[...document.querySelectorAll(".card")];const card=cards.find(c=>c.querySelector("h2")?.textContent.trim()==="Pesquisadores cadastrados");if(!card)return;card.querySelector(".table")?.remove();card.insertAdjacentHTML("beforeend",researcherTable());card.querySelectorAll("[data-copy]").forEach(b=>b.onclick=()=>window.copyLink(b.getAttribute("data-copy")));card.querySelectorAll("[data-reg]").forEach(b=>b.onclick=()=>window.regenerateAccess(b.getAttribute("data-reg")));card.querySelectorAll("[data-del]").forEach(b=>b.onclick=()=>window.deleteResearcher(b.getAttribute("data-del")));};
function patchDirector(){const st=state();const d=st.data||{};if(st.access?.role!=="admin"){const h=[...document.querySelectorAll("h2")].find(x=>x.textContent.trim()==="Aplicativo por função");h?.closest(".card")?.remove();return}const card=[...document.querySelectorAll(".card")].find(c=>c.querySelector("h2")?.textContent.trim()==="Gerar acesso da diretoria");if(!card)return;let box=card.querySelector("#p20-director-links");if(!box){box=document.createElement("div");box.id="p20-director-links";box.style.marginTop="10px";card.appendChild(box)}const links=(d.links||[]).filter(x=>x.role==="director"&&x.active!==false);box.innerHTML=links.length?links.map(x=>x.url?'<div class="notice"><b>'+escv(x.display_name)+'</b><br><small style="word-break:break-all">'+escv(x.url)+'</small><div class="actions" style="margin-top:8px"><button class="btn small" data-copy-dir="'+escv(x.url)+'">Copiar link</button><a class="btn success small" href="'+wa("Acesso Pesquisa 2.0 — Diretoria\n"+x.url+"\nSenha inicial: 1234")+'" target="_blank" rel="noopener">WhatsApp</a></div></div>':'<div class="notice"><b>'+escv(x.display_name)+'</b><br><span class="muted">Link antigo sem URL recuperável.</span><br><br><button class="btn small" data-reg-dir="'+escv(x.id)+'">Gerar novo link</button></div>').join("<br>"):'<div class="notice">Nenhum acesso de diretoria cadastrado.</div>';box.querySelectorAll("[data-copy-dir]").forEach(b=>b.onclick=()=>window.copyLink(b.getAttribute("data-copy-dir")));box.querySelectorAll("[data-reg-dir]").forEach(b=>b.onclick=()=>window.regenerateAccess(b.getAttribute("data-reg-dir")));};
function renderBase(){const st=state(),d=st.data||{};if(st.access?.role!=="admin")return;let host=document.getElementById("p20-persistent-base");if(!host){host=document.createElement("div");host.id="p20-persistent-base";document.querySelector(".content")?.appendChild(host)}const loc=d.locations||[],sec=d.sections||[];const rows=loc.flatMap(l=>sec.filter(x=>x.polling_location_id===l.id).map(x=>'<tr><td>'+escv(l.zone||x.zone||"")+'</td><td>'+escv(l.school_name||"")+'</td><td>'+escv(x.section||"")+'</td><td>'+escv((d.sectors||[]).find(s=>s.id===l.sector_id)?.name||"")+'</td></tr>')).join("");host.innerHTML='<div class="card"><h2>Base gravada no sistema</h2><p class="muted">Esta lista é carregada diretamente do banco e permanece ao trocar de menu.</p>'+(rows?'<div class="table"><table><tr><th>Zona</th><th>Escola</th><th>Seção</th><th>Setor</th></tr>'+rows+'</table></div>':'<div class="notice">Nenhuma base foi gravada ainda.</div>')+'</div>'}
const oldRender=window.render;
if(oldRender){window.render=function(p){oldRender(p);setTimeout(()=>{if(p==="pesquisadores")patchResearchers();if(p==="diretoria")patchDirector();if(p==="importar")renderBase()},0)}}
const oldLoad=window.load;
if(oldLoad){window.load=async function(){const r=await oldLoad();const st=state();if(st.access?.role==="admin"){try{st.data.links=(await window.api("list_links")).links||[]}catch{st.data.links=[]}}return r}}
const oldImport=window.importar;
if(oldImport){window.importar=function(){oldImport();setTimeout(renderBase,0)}}
window.createR=async function(){const name=(document.getElementById("rn")?.value||"").trim(),phone=(document.getElementById("rp")?.value||"").trim(),sector=document.getElementById("rs")?.value;const box=document.getElementById("rm");if(!name){if(box)box.innerHTML='<div class="notice err">Informe o nome do pesquisador.</div>';return}try{const j=await window.api("create_link",{role:"researcher",display_name:name,sector_id:sector,phone});await window.load();window.render("pesquisadores")}catch(e){if(box)box.innerHTML='<div class="notice err">'+escv(e.message)+'</div>'}};
window.createD=async function(){const name=(document.getElementById("dn")?.value||"").trim(),box=document.getElementById("dm");if(!name){if(box)box.innerHTML='<div class="notice err">Informe o nome da diretoria.</div>';return}try{await window.api("create_link",{role:"director",display_name:name});await window.load();window.render("diretoria")}catch(e){if(box)box.innerHTML='<div class="notice err">'+escv(e.message)+'</div>'}};
})();
